language: go

go:
  - 1.4
  - 1.5
  - 1.6
  - 1.7

env:
  matrix:
    - GOOS=linux
    - GOOS=freebsd
    - GOOS=windows

matrix:
  allow_failures:
    go:
      - 1.4

script:
  - go build

notifications:
  email: false
